# Docker Compose file to run containers locally
# launch it with: docker compose -f devop/compose.local.yml up --build

version: "3.9"
name: test-api-service-with-nginx
services:
  api:
    container_name: API
    image: test-api-service
    build:
      context: api service
      dockerfile: Dockerfile
    environment:
      - config_file_path=/devop/config.json
      - server_port=3001
    #ports: 
    #  - 3101:3001
    volumes:
      # /path/on/host:/path/in/container
      - d:/Programming/devop/learning-docker/api-service:/devop
    networks: 
      - my-network

  nginx:
    depends_on: [api]
    container_name: NGINX
    build:
      context: nginx
      dockerfile: Dockerfile
    ports: 
      - 81:80
    networks: 
      - my-network


    
#volumes:
#  devop:
#    name: "Devop-volume"
#    driver: local
#      type: local
#      device: /Programming/devop
#    #external: true

networks:
  my-network:
    driver: bridge