# Docker Compose file for prod
# user that run this script should have ECR permission

version: "3.9"
name: test-api-service
services:
  api:
    hostname: test-api
    container_name: API    
    image: {api-docker-image}
    restart: on-failure
    environment:
      - config_file_path=/devop/config.json
      - server_port=3001
    #ports: 
    #  - 81:3010  # for test
    volumes:
      # /path/on/host:/path/in/container
      - /devop/learning-docker/api-service:/devop
    networks: 
      - my-network
   
  nginx:    
    depends_on: [api]
    container_name: NGINX
    restart: on-failure
    image: {nginx-docker-image}
    ports: 
      - 90:80
    volumes:
      - /devop/learning-docker/nginx/wwwroot:/wwwroot
      - /etc/letsencrypt/live/test.monei.it:/cert
    networks: 
      - my-network

networks:
  my-network:
    driver: bridge