# Docker Compose file for prod

version: "3.9"
name: test-api-service
services:
  api:
    container_name: API
    #image: alessandropiccione/test-api-service:latest
    # user that run this script should have ECR permission
    image: {docker-image}
    restart: on-failure
    environment:
      - config_file_path=/devop/config.json
      - server_port=3010
    ports: 
      - 81:3010
    volumes:
      # /path/on/host:/path/in/container
      - /devop/learning-docker/api-service:/devop

  nginx:
    container_name: nginx
    image: nginx
    restart: on-failure
    #environment:
    

