# Docker Compose file for prod

version: "3.9"
name: test-api-service
services:
  api:
    container_name: API
    image: alessandropiccione/test-api-service:latest
    restart: on-failure
    environment:
      - config_file_path=/devop/config.json
      - server_port=3010
    ports: 
      - 80:3010
    volumes:
      # /path/on/host:/path/in/container
      - /devop/api-service:/devop

