# Linux x64 witin Node (and nothing else!)
FROM node:current-alpine as DEPS

COPY package.json yarn.lock ./

# Install dependencies for production and build
RUN yarn install --frozen-lockfile --production=true
RUN mv ./node_modules/ ./node_modules_production/

RUN yarn install --frozen-lockfile


FROM node:current-alpine as BUILDER

WORKDIR /app

COPY . .

# copy node_modules from dependencies stage
COPY --from=DEPS ./node_modules ./node_modules

# build
RUN yarn build

FROM node:current-alpine as RUNNER

WORKDIR /app

COPY --from=DEPS ./node_modules_production ./node_modules/
COPY --from=BUILDER ./app/build/ ./

ENV PORT 3000
EXPOSE 3000

ENTRYPOINT [ "node", "app.js" ]