# Linux x64 witin Node (and nothing else!)
FROM node:current-alpine as BUILDER

# Create directory in container image for app code
#RUN mkdir -p /app

# Copy the app code (.) to the app directory
COPY . /app
COPY package.json yarn.lock /app

# Copy the builded app code (./build) to the app directory
#COPY ./build /app

# Set working directory context
WORKDIR /app

# Install dependencies
RUN yarn install --frozen-lockfile

# build
RUN yarn build