# Linux x64 witin Node (and nothing else!)
FROM node:current-alpine as BUILD

# Add some metadata
#LABEL bla bla 

# Create directory in container image for app code
RUN mkdir -p /usr/src/app

# Copy the app code (.) to the app directory
COPY . /usr/src/app

# Copy the builded app code (./build) to the app directory
#COPY ./build /usr/src/app

# Set working directory context
WORKDIR /usr/src/app

# Install dependencies
RUN yarn install
RUN yarn build
#RUN yarn install --production=true \
#    && yarn build

RUN npm prune --production
RUN npm ci --only=production

FROM node:current-alpine as MAIN
COPY --from=BUILD /usr/src/app /usr/src/app

EXPOSE 8005

# Command for container to execute
ENTRYPOINT [ "node", "/usr/src/app/build/app.js" ]
