# Linux x64 witin Node (and nothing else!)
FROM node:current-alpine as BUILDER

# Copy the app code (.) to the app directory
COPY . /app

# Copy the builded app code (./build) to the app directory
#COPY ./build /app

# Set working directory context
WORKDIR /app

# Install dependencies
RUN yarn install --frozen-lockfile

# build
RUN yarn build

RUN npm prune --production
RUN npm ci --only=production

FROM node:current-alpine as MAIN
COPY --from=BUILDER /app /app

#USER nextjs

ENV PORT 3000
EXPOSE 3000

# Command for container to execute
ENTRYPOINT [ "node", "/app/build/app.js" ]

# docker run -d -p 8080:3000 --name webapp.1 test:1.1