name: Create Docker image
on: push

env:  
  VERSION: 1.0.${{github.run_number}}

jobs:
  create_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
    
      - name: build
        run: |
          echo build the image using the Dockerfile in webapp folder
          cd webapp
          docker image build -t ${{secrets.DOCKERHUB_USERID}}/webapp:$VERSION .
          docker image build -t ${{secrets.DOCKERHUB_USERID}}/webapp:latest .
          echo ---
          echo Docker login
          echo ${{secrets.DOCKERHUB_PWD}} | docker login -u ${{secrets.DOCKERHUB_USERID}}
          echo ---
          echo push the image on dockerhub
          docker image push ${{secrets.DOCKERHUB_USERID}}/webapp:$VERSION
          docker image push ${{secrets.DOCKERHUB_USERID}}/webapp:latest
