name: Create API-service test Docker image
on: push

env:    
  REPO: ${{secrets.DOCKERHUB_USERID}}
  IMAGE: test-api-service
  VERSION: 2.2.${{github.run_number}}

jobs:
  create_image:
    name: Create Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
    
      - name: build
        run: |
          echo build the image using the Dockerfile in examples/api-service folder
          docker image build -t $IMAGE:0 -f "./examples/api service/Dockerfile" "./examples/api service"
          echo ---
      - name: publish
        run: |
          echo DockerHub login and Push image "$IMAGE:$VERSION"
          #echo ${{secrets.DOCKERHUB_PWD}} | docker login -u ${{secrets.DOCKERHUB_USERID}} $DOCKERHUB_URL --password-stdin   
          echo ${{secrets.DOCKERHUB_PWD}} | docker login -u ${{secrets.DOCKERHUB_USERID}} --password-stdin   
          docker image tag $IMAGE:0 $REPO/$IMAGE:$VERSION
          docker image tag $IMAGE:0 $REPO/$IMAGE:latest               
          docker image push $REPO/$IMAGE:$VERSION 
          docker image push $REPO/$IMAGE:latest
          echo ---
