name: Create Docker image
on: push

env:  
  VERSION: 1.0.${{github.run_number}}

jobs:
  create_image:
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: |
          ls > echo
          cd webapp
          docker image build -t webapp:$VERSION .
