name: Create Docker image
on: push

env:  
  VERSION: 1.0.${{github.run_number}}
  CANISTER_URL: cloud.canister.io:5000
  REPO: test-1

jobs:
  create_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
    
      - name: build
        run: |
          echo build the image using the Dockerfile in webapp folder
          cd webapp
          docker image build -t webapp:$VERSION .
          docker image build -t webapp:latest .
          echo ---
          echo TODO echo docker.pkg.github.com
          echo ---
          #echo Docker login and Push
          #echo ${{secrets.DOCKERHUB_PWD}} | docker login -u ${{secrets.DOCKERHUB_USERID}} --password-stdin
          #docker image push ${{secrets.DOCKERHUB_USERID}}/webapp:$VERSION
          #docker image push ${{secrets.DOCKERHUB_USERID}}/webapp:latest
          echo ---
          echo Canister login and Push
          echo re-tag the images 
          docker image tag webapp:$VERSION $CANISTER_URL/${{secrets.CANISTER_USERID}}/$REPO/webapp:$VERSION
          docker image tag webapp:latest   $CANISTER_URL/${{secrets.CANISTER_USERID}}/$REPO/webapp:latest
          echo ${{secrets.CANISTER_PWD}} | docker login -u deploy+${{secrets.CANISTER_USERID}} $CANISTER_URL --password-stdin          
          docker image push $CANISTER_URL/${{secrets.CANISTER_USERID}}/$REPO/webapp:$VERSION 
          docker image push $CANISTER_URL/${{secrets.CANISTER_USERID}}/$REPO/webapp:latest
          echo ---

