name: Create Docker image of "Node webapp 1"
on: push

env:   
  IMAGE: test-webapp
  VERSION: 1.0.${{github.run_number}}
  CANISTER_URL: cloud.canister.io:5000
  CR_URL: c8n.io
  SRC_PATH: examples/node webapp 1


jobs:
  create_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
    
      - name: build
        run: |
          echo "### Build the image using the Dockerfile in webapp folder ###"
          cd "$SRC_PATH"
          docker image build -t $IMAGE:0 -f "devops/Dockerfile.3" .
          echo ---
          
          #echo "### docker.pkg.github.com"
          #echo ---
          #echo Docker login and Push
          #echo ${{secrets.DOCKERHUB_PWD}} | docker login -u ${{secrets.DOCKERHUB_USERID}} --password-stdin
          #docker image push ${{secrets.DOCKERHUB_USERID}}/$REPO:$VERSION
          #docker image push ${{secrets.DOCKERHUB_USERID}}/$REPO:latest
          #echo ---
          
          echo "### Canister login and Push"
          echo ${{secrets.CANISTER_PWD}} | docker login -u ${{secrets.CANISTER_USERID}} $CANISTER_URL --password-stdin   
          docker image tag $IMAGE:0 $CANISTER_URL/${{secrets.CANISTER_USERID}}/$IMAGE:$VERSION
          docker image tag $IMAGE:0 $CANISTER_URL/${{secrets.CANISTER_USERID}}/$IMAGE:latest                 
          docker image push $CANISTER_URL/${{secrets.CANISTER_USERID}}/$IMAGE:$VERSION 
          docker image push $CANISTER_URL/${{secrets.CANISTER_USERID}}/$IMAGE:latest
          docker image pull $CANISTER_URL/${{secrets.CANISTER_USERID}}/$IMAGE:latest
          echo ---
          
          echo "### Container Registry (c8n.io) login and Push"
          echo ${{secrets.CR_PWD}} | docker login -u ${{secrets.CR_USERID}} $CR_URL --password-stdin          
          docker image tag $IMAGE:0 $CR_URL/${{secrets.CR_USERID}}/$IMAGE:$VERSION
          docker image tag $IMAGE:0 $CR_URL/${{secrets.CR_USERID}}/$IMAGE:latest          
          docker image push $CR_URL/${{secrets.CR_USERID}}/$IMAGE:$VERSION 
          docker image push $CR_URL/${{secrets.CR_USERID}}/$IMAGE:latest
          echo ---
